//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webbanhang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDonHang
    {
        public int MaDDH { get; set; }
        public int IDSP { get; set; }
        public string TenSP { get; set; }
        public float Soluong { get; set; }
        public Nullable<float> DonGia { get; set; }
    
        public virtual DonDatHangg DonDatHangg { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
