//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webbanhang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonDatHangg
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonDatHangg()
        {
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
        }
    
        public Nullable<System.DateTime> NgayDat { get; set; }
        public Nullable<byte> TinhTrangGiao { get; set; }
        public Nullable<byte> DaThanhToan { get; set; }
        public int MaTV { get; set; }
        public string UuDai { get; set; }
        public Nullable<System.DateTime> NgayGiao { get; set; }
        public int MaDDH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual ThanhVien ThanhVien { get; set; }
    }
}
